version: '3.8'

services:
  api:
    build:
      context: ./api/InvoiceApp.API
      dockerfile: Dockerfile
    ports:
      - "7290:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__dbcs=Server=db;Database=PersonalDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
      - JwtConfig__Issuer=https://localhost:7290/
      - JwtConfig__Audience=https://localhost:7290/
      - JwtConfig__Key=ThisIsAStrongJwtSecretKey1234567890!
      - ALLOWED_ORIGINS=http://localhost:8080,http://localhost:3000
    depends_on:
      - db
    networks:
      - app-network

  ui:
    build:
      context: ./ui/ui-main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:7290
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge
