
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InvoiceApp.API.Models
{
    [Table("Expenses")]
    public class Expense
    {
        [Key]
        public Guid Id { get; set; }   
        [Required]
        [MaxLength(100)]
        public string Title { get; set; }

        [Required]
        public string ExpenseNumber { get; set; }//generated by backend

        [Required]
        [Range(0, double.MaxValue)]
        public decimal Amount { get; set; }  // Expense amount

        [Required]
        public DateTime ExpenseDate { get; set; }  // Date of expense

        [MaxLength(50)]
        public string Category { get; set; }  // e.g., Rent, Utilities, Travel, etc.

        [MaxLength(50)]
        public string PaymentMethod { get; set; } // e.g., Cash, Credit Card, Bank Transfer

        [MaxLength(250)]
        public string? Notes { get; set; }  // Optional notes/details

        [Required]
        [MaxLength(50)]
        public string CreatedBy { get; set; }  // User who created

        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow; // Auto set when created

        [MaxLength(50)]
        public string? UpdatedBy { get; set; }  // User who last updated

        public DateTime? UpdatedAt { get; set; } // Nullable (only when updated)

        [MaxLength(50)]
        public string? DeletedBy { get; set; }  // User who deleted (if soft delete)

        public DateTime? DeletedAt { get; set; } // Nullable (if deleted)

        public string Action { get; set; } // Soft delete flag
    }
}
