using System;
using System.ComponentModel.DataAnnotations;

public class ExpenseBaseModel
{
    [Required]
    public string Title { get; set; }
    public string? ExpenseNumber { get; set; }//generated by backend


    [Required]
    public decimal Amount { get; set; }

    [Required]
    public string Category { get; set; }   // e.g., Rent, Utilities, Travel, etc.
    [MaxLength(50)]
    public string? PaymentMethod { get; set; }
    [Required]
    public DateTime ExpenseDate { get; set; }

    public string? Action { get; set; }  // A / E / D
    public string? Notes { get; set; }
}

public class ExpenseAddModel : ExpenseBaseModel
{
}

public class ExpenseUpdateModel : ExpenseBaseModel
{
    [Required]
    public Guid Id { get; set; }
}

public class ExpenseDeleteModel
{
    [Required]
    public Guid Id { get; set; }
}

public class ExpenseViewModel : ExpenseBaseModel
{
    public Guid Id { get; set; }
}

public class ExpenseViewByIdModel : ExpenseBaseModel
{
    public Guid Id { get; set; }
}
